"""R2-0 Prompt 5: final synthesis — master evidence table (read-only).

Reads NO new experiments; every row below is a frozen conclusion verified
against the R0 / R1 / R1.5 / R2-0A / R2-0B / R2-0C CSVs & reports (see the
source_file column). Evidence levels:

    L1 Intermediate Representation Evidence (factor/context-layer probes)
    L2 Local-complete / correspondence-controlled Evidence
    L3 Final Residual Evidence ([z_final | ...] probes)
    L4 End-to-end Training Evidence (R1 / R1.5 trained variants)

Output: outputs/perf_r20/summary/R20_MASTER_TABLE.csv
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.analysis.perf_r20_utils import write_csv  # noqa: E402

OUT_ROOT = PROJECT_ROOT / "outputs" / "perf_r20" / "summary"

# (stage, hypothesis, dataset, metric, level, mean_pp, std_pp, pos_seeds,
#  verdict, interpretation, r2_implication, source)
ROWS: list[tuple] = [
    # ---------------------------------------------------------------- R0 anchors
    ("R0", "router/selection 惰性 (Δ_sel)", "M/T/G 5 datasets", "ValAcc",
     "L1", -0.02, 0.06, 1, "NO EVIDENCE",
     "Δ_sel ≈ 0 全部 5 数据集；corr(α,Q) ≤ 0.084；soft mixing 必需（hard top-1 全负）",
     "Γ/relation-selection 不作为 R2 核心机制（见 E 关闭）",
     "outputs/perf_r0/summary/R0_FINAL_DIAGNOSIS.md"),
    ("R0", "Local state 机制价值 (Δ_local)", "Movies/Grocery/ele-fashion", "ValAcc",
     "L2", 1.75, 0.35, 3, "MODERATE",
     "Δ_local Movies +2.01 / Grocery +1.28 / ele-fashion +1.97（macro 1.75）",
     "local residual preservation 保留（KEEP）",
     "outputs/perf_r0/summary/R0_MASTER_TABLE.csv"),
    ("R0", "multi-hop 潜力 (Δ_hop2)", "Movies", "ValAcc",
     "L1", 0.34, 0.0, 1, "MODERATE",
     "Movies +0.34；其余 ≤ +0.30；1-hop 基本榨干",
     "multi-hop 仅条件保留（D 候选 LOW/OPTIONAL）",
     "outputs/perf_r0/summary/R0_MASTER_TABLE.csv"),
    # ---------------------------------------------------------------- R2-0A
    ("R2-0A", "off-diagonal transfer C→Pt (Adv vs same-factor)", "Movies", "ValAcc",
     "L1", 5.16, 0.76, 3, "STRONG", "plain 3x3 dimension-matched；F1 +9.9pp",
     "target Pt 应可消费 neighbor C 源（target-conditioned transfer）",
     "outputs/perf_r20/cross_factor/R20_A_CROSS_FACTOR_REPORT.md"),
    ("R2-0A", "off-diagonal transfer C→Pt (Adv vs same-factor)", "Toys", "ValAcc",
     "L1", 5.02, 0.13, 3, "STRONG", "plain；relation kind +4.98 一致",
     "同左；跨数据集稳定",
     "outputs/perf_r20/cross_factor/R20_A_CROSS_FACTOR_REPORT.md"),
    ("R2-0A", "off-diagonal transfer C→Pt (Adv vs same-factor)", "Grocery", "ValAcc",
     "L1", 3.70, 0.35, 3, "STRONG", "plain；relation kind +3.70 一致",
     "同左；3/3 数据集稳定",
     "outputs/perf_r20/cross_factor/R20_A_CROSS_FACTOR_REPORT.md"),
    ("R2-0A", "off-diagonal transfer Pv→Pt (Adv vs same-factor)", "Movies", "ValAcc",
     "L1", 5.97, 0.88, 3, "STRONG", "F1 +13.2pp；diag Pt→Pt 为最弱 cell",
     "visual-private 邻居对 Pt 目标有强 utility",
     "outputs/perf_r20/cross_factor/R20_A_CROSS_FACTOR_REPORT.md"),
    ("R2-0A", "off-diagonal transfer Pv→Pt (Adv vs same-factor)", "Toys", "ValAcc",
     "L1", 4.41, 0.24, 3, "STRONG", "F1 +6.5pp",
     "同左",
     "outputs/perf_r20/cross_factor/R20_A_CROSS_FACTOR_REPORT.md"),
    ("R2-0A", "off-diagonal transfer Pv→Pt (Adv vs same-factor)", "Grocery", "ValAcc",
     "L1", 3.17, 0.79, 3, "STRONG", "F1 +3.4pp",
     "同左",
     "outputs/perf_r20/cross_factor/R20_A_CROSS_FACTOR_REPORT.md"),
    ("R2-0A", "off-diagonal transfer C→Pv (Adv vs same-factor)", "Toys/Grocery", "ValAcc",
     "L1", 2.58, 0.05, 3, "STRONG", "Toys +2.59(3)/Grocery +2.57(3)；Movies −0.77 不成立",
     "C→Pv 条件性成立（2/3 数据集）",
     "outputs/perf_r20/cross_factor/R20_A_CROSS_FACTOR_REPORT.md"),
    ("R2-0A", "off-diagonal transfer Pv→C (Adv vs same-factor)", "Movies", "ValAcc",
     "L1", 1.31, 0.21, 3, "MODERATE", "仅 Movies 成立（F1 +3.8pp）",
     "Movies 的 visual-private → common 通路",
     "outputs/perf_r20/cross_factor/R20_A_CROSS_FACTOR_REPORT.md"),
    ("R2-0A", "all-local conditioned graph info (A4, vs L=[C|Pt|Pv])", "Movies", "ValAcc",
     "L2", 2.71, 0.46, 3, "STRONG", "all-source plain；单源 N^C +1.50 / N^Pv +2.63 也 3/3",
     "local semantics 全部可见后 neighbor source 仍有额外信息",
     "outputs/perf_r20/cross_factor/cross_factor_local_conditioned.csv"),
    ("R2-0A", "all-local conditioned graph info (A4, vs L=[C|Pt|Pv])", "Toys", "ValAcc",
     "L2", 5.03, 0.62, 3, "STRONG", "单源 N^C/N^Pt/N^Pv 全 3/3 正",
     "同左",
     "outputs/perf_r20/cross_factor/cross_factor_local_conditioned.csv"),
    ("R2-0A", "all-local conditioned graph info (A4, vs L=[C|Pt|Pv])", "Grocery", "ValAcc",
     "L2", 5.28, 0.15, 3, "STRONG", "单源全 3/3 正",
     "同左",
     "outputs/perf_r20/cross_factor/cross_factor_local_conditioned.csv"),
    ("R2-0A", "shuffle negative control (A4/A1 real−shuffled)", "Movies", "ValAcc",
     "L2", 4.53, 0.65, 3, "STRONG", "intermediate 层 real−shuffled 全 3/3 正",
     "graph utility 是真实 neighbor correspondence 而非高维假象",
     "outputs/perf_r20/cross_factor/cross_factor_shuffle_control.csv"),
    ("R2-0A", "shuffle negative control (A4/A1 real−shuffled)", "Toys", "ValAcc",
     "L2", 6.21, 0.50, 3, "STRONG", "同左",
     "同左",
     "outputs/perf_r20/cross_factor/cross_factor_shuffle_control.csv"),
    ("R2-0A", "shuffle negative control (A4/A1 real−shuffled)", "Grocery", "ValAcc",
     "L2", 6.03, 0.17, 3, "STRONG", "同左",
     "同左",
     "outputs/perf_r20/cross_factor/cross_factor_shuffle_control.csv"),
    ("R2-0A", "z_final plain-neighbor residual (A5 all-source)", "Movies", "ValAcc",
     "L3", 0.19, 0.28, 2, "NO EVIDENCE", "relation kind −0.40(0) 更弱",
     "plain neighbor info 已被 factor-wise propagation + late fusion 基本吸收；不可把 A 的 intermediate headroom 当最终可兑现空间",
     "outputs/perf_r20/cross_factor/cross_factor_final_incremental.csv"),
    ("R2-0A", "z_final plain-neighbor residual (A5 all-source)", "Toys", "ValAcc",
     "L3", 0.19, 0.09, 3, "WEAK", "relation kind +0.02(1)",
     "同左",
     "outputs/perf_r20/cross_factor/cross_factor_final_incremental.csv"),
    ("R2-0A", "z_final plain-neighbor residual (A5 all-source)", "Grocery", "ValAcc",
     "L3", -0.15, 0.05, 0, "NO EVIDENCE", "relation kind −0.18(1)",
     "同左",
     "outputs/perf_r20/cross_factor/cross_factor_final_incremental.csv"),
    # ---------------------------------------------------------------- R2-0B
    ("R2-0B", "explicit basis > current K4 (per-factor Δ_B^f)", "Movies", "ValAcc",
     "L1", 1.35, 0.49, 3, "STRONG", "Pt 最强（+1.35）；C +0.44 / Pv +0.45；F1 secondary 正",
     "single-factor 层 explicit 4-channel 优于 latent K4，但联合后冗余（见 L2）",
     "outputs/perf_r20/structural_basis/structural_context_probe_per_factor.csv"),
    ("R2-0B", "explicit basis > current K4 (per-factor Δ_B^f)", "Toys", "ValAcc",
     "L1", 2.50, 0.30, 3, "STRONG", "Pt 最强（+2.50）",
     "同左",
     "outputs/perf_r20/structural_basis/structural_context_probe_per_factor.csv"),
    ("R2-0B", "explicit basis > current K4 (per-factor Δ_B^f)", "Grocery", "ValAcc",
     "L1", 1.55, 0.50, 3, "STRONG", "Pt 最强（+1.55）",
     "同左",
     "outputs/perf_r20/structural_basis/structural_context_probe_per_factor.csv"),
    ("R2-0B", "joint Δ_B_intermediate (explicit 15d − current 15d)", "Movies", "ValAcc",
     "L2", 0.33, 0.35, 2, "WEAK", "F1 +1.95pp(3) secondary 正",
     "三 factor 联合后两套 basis 高度冗余；Advantage 不构成 final bottleneck",
     "outputs/perf_r20/structural_basis/structural_context_probe_joint.csv"),
    ("R2-0B", "joint Δ_B_intermediate (explicit 15d − current 15d)", "Toys", "ValAcc",
     "L2", 0.64, 0.32, 3, "GO", "F1 +1.02pp(3)",
     "同左",
     "outputs/perf_r20/structural_basis/structural_context_probe_joint.csv"),
    ("R2-0B", "joint Δ_B_intermediate (explicit 15d − current 15d)", "Grocery", "ValAcc",
     "L2", -0.32, 0.10, 0, "NO-GO", "F1 −0.26pp(1)",
     "同左",
     "outputs/perf_r20/structural_basis/structural_context_probe_joint.csv"),
    ("R2-0B", "2-hop channel G2 vs G1（per-factor，Pt 因子）", "Movies", "ValAcc",
     "L1", 1.40, 0.21, 3, "STRONG", "Pt 因子 G2>G1 3/3 数据集 × 3/3 seeds",
     "多跳信息仅对 Pt 轨迹有条件价值（D 候选 OPTIONAL 依据）",
     "outputs/perf_r20/structural_basis/structural_single_channel_per_factor.csv"),
    ("R2-0B", "2-hop channel G2 vs G1（per-factor，Pt 因子）", "Toys", "ValAcc",
     "L1", 1.92, 0.34, 3, "STRONG", "同左",
     "同左",
     "outputs/perf_r20/structural_basis/structural_single_channel_per_factor.csv"),
    ("R2-0B", "2-hop channel G2 vs G1（per-factor，Pt 因子）", "Grocery", "ValAcc",
     "L1", 1.05, 0.59, 3, "STRONG", "同左",
     "同左",
     "outputs/perf_r20/structural_basis/structural_single_channel_per_factor.csv"),
    ("R2-0B", "joint 2-hop / sim / diff vs G1", "M/T/G macro", "ValAcc",
     "L2", -0.09, 0.49, 1, "NO EVIDENCE", "Δ_hop −0.09 / Δ_sim −0.05 / Δ_diff −0.34（joint 层）",
     "Gsim/Gdiff 无稳定价值；joint 层无通用 multi-hop gain",
     "outputs/perf_r20/structural_basis/R20_B_STRUCTURAL_BASIS_REPORT.md"),
    ("R2-0B", "Δ_B_final (explicit − current, h+12d matched)", "Movies", "ValAcc",
     "L3", 0.33, 0.58, 2, "WEAK", "F1 +1.69pp(3)；H_explicit_final 仅 −0.06",
     "final 层 explicit 略优于 current（Movies 上 current 有害 −0.39），但非新 headroom",
     "outputs/perf_r20/structural_basis/structural_final_residual.csv"),
    ("R2-0B", "Δ_B_final (explicit − current, h+12d matched)", "Toys", "ValAcc",
     "L3", 0.22, 0.13, 3, "WEAK", "F1 +0.39pp(3)",
     "同左",
     "outputs/perf_r20/structural_basis/structural_final_residual.csv"),
    ("R2-0B", "Δ_B_final (explicit − current, h+12d matched)", "Grocery", "ValAcc",
     "L3", 0.14, 0.07, 3, "WEAK", "F1 +0.38pp(3)",
     "同左",
     "outputs/perf_r20/structural_basis/structural_final_residual.csv"),
    ("R2-0B", "H_explicit_final = [z_final|B_explicit] − z_final", "M/T/G macro", "ValAcc",
     "L3", 0.05, 0.14, 2, "NO EVIDENCE", "Movies −0.06 / Toys +0.24 / Grocery −0.04",
     "z_final 已吸收 explicit structural info；扩充 channel 不是 final 解法",
     "outputs/perf_r20/structural_basis/structural_final_residual.csv"),
    # ---------------------------------------------------------------- R2-0C
    ("R2-0C", "common branch [c_t|c_v] vs fixed C=0.5(c_t+c_v)", "Movies", "ValAcc",
     "L1", 0.75, 0.30, 3, "MODERATE", "dimension 不匹配 → headroom diagnostic 非 causal",
     "fixed averaging 存在信息压缩，但为 secondary weakness",
     "outputs/perf_r20/semantic_interaction/common_representation_probe.csv"),
    ("R2-0C", "common branch [c_t|c_v] vs fixed C=0.5(c_t+c_v)", "Toys", "ValAcc",
     "L1", 1.11, 0.39, 3, "STRONG", "同左",
     "同左",
     "outputs/perf_r20/semantic_interaction/common_representation_probe.csv"),
    ("R2-0C", "common branch [c_t|c_v] vs fixed C=0.5(c_t+c_v)", "Grocery", "ValAcc",
     "L1", 1.42, 0.28, 3, "STRONG", "同左",
     "同左",
     "outputs/perf_r20/semantic_interaction/common_representation_probe.csv"),
    ("R2-0C", "C1 primary: factor interaction − z_local", "Movies", "ValAcc",
     "L2", 0.55, 0.09, 3, "GO", "F1 +2.42pp(3)；node-correspondence 对照 +2.02(3)",
     "node-local interaction 有 headroom；但 dim 不匹配 → headroom evidence 非端到端预期",
     "outputs/perf_r20/semantic_interaction/semantic_factor_interaction_probe.csv"),
    ("R2-0C", "C1 primary: factor interaction − z_local", "Toys", "ValAcc",
     "L2", 1.30, 0.39, 3, "STRONG", "node-correspondence 对照 +1.39(3)",
     "同左",
     "outputs/perf_r20/semantic_interaction/semantic_factor_interaction_probe.csv"),
    ("R2-0C", "C1 primary: factor interaction − z_local", "Grocery", "ValAcc",
     "L2", 1.39, 0.06, 3, "STRONG", "node-correspondence 对照 +0.75(3)",
     "同左",
     "outputs/perf_r20/semantic_interaction/semantic_factor_interaction_probe.csv"),
    ("R2-0C", "C1 correspondence control (inter − shuffled I_factor)", "M/T/G macro", "ValAcc",
     "L2", 1.39, 0.52, 3, "STRONG", "F1 +4.49pp；same-node semantic correspondence 真实",
     "正确配对（而非维度）是关键；refinement 须在 graph propagation 之前",
     "outputs/perf_r20/semantic_interaction/semantic_interaction_shuffle_control.csv"),
    ("R2-0C", "modal interaction [h_t|h_v|I_modal] − [h_t|h_v]", "M/T/G macro", "ValAcc",
     "L2", 0.82, 0.22, 3, "STRONG", "real−mismatch +1.57(3/3 ds)；Movies +0.98",
     "text-image 同节点对应关系有价值",
     "outputs/perf_r20/semantic_interaction/semantic_modal_interaction_probe.csv"),
    ("R2-0C", "C3 L-conditioned interaction Δ_L (stable cell C→C)", "M/T/G macro", "ValAcc",
     "L2", 0.89, 0.30, 3, "STRONG", "3/3 数据集；Specific（real−mismatch）全正；F1 +2.56pp",
     "target×source 兼容性含 task 信息（capacity 成分见 caveat）",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_local_complete.csv"),
    ("R2-0C", "C3 L-conditioned interaction Δ_L (stable cell C→Pt)", "M/T/G macro", "ValAcc",
     "L2", 0.63, 0.22, 3, "STRONG", "3/3 数据集；Specific 全正；F1 +1.80pp",
     "预注册 focus cell 兑现",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_local_complete.csv"),
    ("R2-0C", "C3 L-conditioned interaction Δ_L (stable cell Pt→C)", "M/T/G macro", "ValAcc",
     "L2", 0.62, 0.28, 3, "STRONG", "3/3 数据集；Specific 全正；F1 +1.49pp",
     "同左",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_local_complete.csv"),
    ("R2-0C", "C3 L-conditioned interaction Δ_L (stable cell Pt→Pt)", "M/T/G macro", "ValAcc",
     "L2", 0.77, 0.09, 3, "STRONG", "3/3 数据集；Specific 全正；F1 +1.76pp",
     "同左",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_local_complete.csv"),
    ("R2-0C", "C3 L-conditioned interaction Δ_L (stable cell Pv→C)", "Grocery/Movies", "ValAcc",
     "L2", 0.90, 0.42, 3, "STRONG", "Grocery +0.48(3)/Movies +1.32(3)；Specific 全正；F1 +2.55pp",
     "预注册 focus cell 兑现（2/3 数据集）",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_local_complete.csv"),
    ("R2-0C", "C3 L-conditioned interaction Δ_L (stable cell Pv→Pt)", "Grocery/Movies", "ValAcc",
     "L2", 0.93, 0.50, 3, "STRONG", "Grocery +0.43(3)/Movies +1.42(3)；Specific 全正；F1 +2.11pp",
     "预注册 focus cell 兑现（2/3 数据集）",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_local_complete.csv"),
    ("R2-0C", "C3 focus cell C→Pv（未兑现）", "Toys/Grocery", "ValAcc",
     "L2", 0.10, 0.25, 2, "NO EVIDENCE", "Toys +0.10(1)/Grocery +0.10(2)；仅 Movies +0.85(3) 有交互 headroom",
     "C→Pv 的 cross-factor utility 不需显式交互即可获得（A 的 concat 已够）",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_local_complete.csv"),
    ("R2-0C", "C2 final residual H_factor/modal/common", "M/T/G macro", "ValAcc",
     "L3", 0.16, 0.01, 2, "WEAK", "factor +0.15 / modal +0.16 / common +0.17",
     "node-local interaction 不能作为 final 前 feature concat；必须 pre-propagation",
     "outputs/perf_r20/semantic_interaction/semantic_final_residual.csv"),
    ("R2-0C", "Level-VI H_cond_inter_final (Pv→C)", "Movies", "ValAcc",
     "L3", 0.75, 0.27, 3, "STRONG", "F1 +1.83pp；Specific +0.51(3)",
     "Movies：A0 未充分编码 visual-private neighbor × target common 交互",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_final_residual.csv"),
    ("R2-0C", "Level-VI H_cond_inter_final (Pv→Pt)", "Movies", "ValAcc",
     "L3", 0.47, 0.13, 3, "STRONG", "F1 +1.13pp",
     "同左（Movies Pv-source 残差族）",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_final_residual.csv"),
    ("R2-0C", "Level-VI H_cond_inter_final (Pv→Pv)", "Movies", "ValAcc",
     "L3", 0.33, 0.34, 2, "MODERATE", "F1 +0.62pp",
     "同左",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_final_residual.csv"),
    ("R2-0C", "Level-VI H_cond_inter_final (Pt→Pt)", "Toys", "ValAcc",
     "L3", 0.20, 0.04, 3, "MODERATE", "Toys/Grocery final residual 总体较弱",
     "Toys/Grocery 主要是 intermediate inductive-bias evidence",
     "outputs/perf_r20/semantic_interaction/graph_conditioned_final_residual.csv"),
    # ---------------------------------------------------------------- R1 (L4)
    ("R1", "factor-conditioned edge reliability A1 (η)", "M/T/G macro", "ValAcc",
     "L4", -0.19, 0.19, 1, "NO-GO", "Movies −0.34(1)/Toys +0.01(2)/Grocery −0.23(2)；guards OK；η 塌缩+梯度耦合",
     "scalar edge reliability 关闭（机制冻结价值真实但训练级收益负）",
     "outputs/perf_r1/summary/R1_A_REPORT.md"),
    ("R1", "reliability + 正则变体 A1R1..R4", "M/T/G macro", "ValAcc",
     "L4", -0.08, 0.03, 0, "NO-GO", "4 变体 −0.05~−0.11；正则阻止塌缩但不恢复性能",
     "reliability 选择性本身不携带增益",
     "outputs/perf_r1/summary/R1_A_A1-A1R1-A1R2-A1R3-A1R4_REPORT.md"),
    ("R1", "relation calibration A2 (factor-conditioned r)", "M/T/G seed42", "ValAcc",
     "L4", -0.02, 0.13, 1, "NO-GO", "Movies −0.12/Toys +0.145/Grocery −0.09；机制分化真实但无 Val 收益",
     "relation posterior 校准关闭",
     "outputs/perf_r1/summary/R1_A_A2_REPORT.md"),
    ("R1", "router 残差解耦 BL（dynamic local）", "M/T/G seed42", "ValAcc",
     "L4", -0.13, 0.24, 1, "NO-GO", "Grocery −0.44",
     "local 路由残差关闭",
     "outputs/perf_r1/summary/R1_A_BL-BR-BLR_REPORT.md"),
    ("R1", "router 残差解耦 BR（support relation）", "M/T/G seed42", "ValAcc",
     "L4", -0.15, 0.23, 1, "NO-GO", "Movies −0.48；Grocery Δ_sel +0.26 但 Val 仍负",
     "relation 路由残差关闭",
     "outputs/perf_r1/summary/R1_A_BL-BR-BLR_REPORT.md"),
    ("R1", "router 残差组合 BLR（evidence）", "M/T/G 3-seed", "ValAcc",
     "L4", 0.06, 0.16, 2, "NO-GO", "seed42 +0.34 未复现；Reddit-S +0.20(3) 最稳但 M/T/G 不达标",
     "evidence-aware Γ 关闭（J-series 冻结价值真实但训练不可复现）",
     "outputs/perf_r1/summary/R1_A_BLR_REPORT.md"),
    ("R1", "detached 2-hop C1SG", "Movies/Toys seed42", "ValAcc",
     "L4", -0.38, 0.42, 1, "NO-GO", "Toys −0.80、Grocery −0.82 破 guard；learned-λ vs λ=0 冻结为正",
     "浅层 2-hop 训练变体关闭",
     "outputs/perf_r1/summary/R1_A_C1SG_REPORT.md"),
    ("R1", "J-series 冻结反事实（同 checkpoint）", "M/T/G macro", "ValAcc",
     "L4", 0.64, 0.32, 3, "MECHANISM-ONLY",
     "J0−J3 全正（Movies +1.07/Toys +0.31/Grocery +0.54）但训练级不可复现 → 机制价值≠训练收益",
     "R2 设计必须注意：模块冻结价值不能作为训练收益承诺",
     "outputs/perf_r1/summary/R1_A_BLR_REPORT.md"),
    # ---------------------------------------------------------------- R1.5 (L4)
    ("R1.5", "LR×WD 8 组 tuning", "M/T/G macro", "ValAcc",
     "L4", 0.06, 0.10, 2, "CLOSED", "最优 lr3e-4_wd0 +0.06；lr3e-3 灾难 −1.7",
     "训练/超参不解释性能差距（G 关闭）",
     "outputs/perf_r15/R15_FINAL_SYNTHESIS.md"),
    ("R1.5", "capacity 变体 C1-C3", "M/T/G macro", "ValAcc",
     "L4", -0.30, 0.11, 0, "CLOSED", "−0.15/−0.41/−0.35；C4 显存拒绝",
     "operator/fusion 容量扩充关闭（F 关闭）",
     "outputs/perf_r15/R15_FINAL_SYNTHESIS.md"),
    ("R1.5", "aux-loss 再平衡 / warmup-cosine", "M/T/G macro", "ValAcc",
     "L4", -0.14, 0.09, 0, "CLOSED", "λc=0.05 / λc+λr / warmup_cosine 全负",
     "aux/objective 再平衡关闭",
     "outputs/perf_r15/R15_FINAL_SYNTHESIS.md"),
    ("R1.5", "frozen-A0 2-hop adapter D1", "M/T/G 9 seeds", "ValAcc",
     "L4", 0.00, 0.00, 0, "CLOSED", "DA2−DA0 = 0.00（9/9）→ 第二跳无可学增量",
     "multi-hop 默认关闭；仅 Pt 条件信号保留 OPTIONAL",
     "outputs/perf_r15/R15_FINAL_SYNTHESIS.md"),
    ("R1.5", "structural observation 扩展 D2 (S+ vs S3)", "M/T/G macro", "ValAcc",
     "L4", -0.01, 0.11, 1, "CLOSED", "−0.18/+0.07/+0.09，0/3 ≥ +0.3",
     "结构观察带宽扩展无 headroom 证据（C 关闭佐证）",
     "outputs/perf_r15/R15_FINAL_SYNTHESIS.md"),
]


def main() -> None:
    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    rows = [
        {
            "stage": r[0], "hypothesis": r[1], "dataset": r[2], "metric": r[3],
            "evidence_level": r[4], "mean_delta_pp": r[5], "std_pp": r[6],
            "positive_seeds": r[7], "verdict": r[8], "interpretation": r[9],
            "r2_implication": r[10], "source_file": r[11],
        }
        for r in ROWS
    ]
    write_csv(OUT_ROOT / "R20_MASTER_TABLE.csv", rows)
    print(f"[r20-summary] {len(rows)} rows -> {OUT_ROOT / 'R20_MASTER_TABLE.csv'}")


if __name__ == "__main__":
    main()
